title: Liwen Yang
email: liwenyang@whu.edu.cn
description: Liwen Yang's academic homepage.
baseurl: ""
url: "https://1yangliwen.github.io"
timezone: Asia/Shanghai
lang: en
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
collections: {}
defaults:
  - scope:
      path: ""
    values:
      layout: default
